### ISSUE TITLE
2022 Todo

### ISSUE THREAD

**Issue by Clam-** [Clam-/ConfApp#13]
- [x] Add hover over for Building number to give building name in tooltip
- [x] Add hover over for presenter names to show phone number(s)
- [x] Add session parsing DONE
- [x] Add presenter parsing... kinda done?? regret incident
- [x] Check host parsing... need host list though ???
